source 'https://github.com/CocoaPods/Specs.git'

target 'MZRPresentationKit', :exclusive => true do
  pod "MZRPresentationKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MZRPresentationKit", :path => "../"

  
end
